# Generated by Django 6.0.4 on 2026-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_investmentproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproduct',
            name='min_investment',
        ),
        migrations.RemoveField(
            model_name='investmentproduct',
            name='performance_note',
        ),
        migrations.RemoveField(
            model_name='investmentproduct',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='investmentproduct',
            name='short_description',
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='estimated_gain_cdf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gain estimé en FC (NON GARANTI). Ne pas présenter comme une promesse.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='min_investment_cdf',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Montant minimum en FC', max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='note',
            field=models.CharField(choices=[('TRUSTED', 'Fiable'), ('MAYBE', 'Pas vraiment'), ('POPULAR', 'Populaire')], default='POPULAR', max_length=10),
        ),
    ]
