# Generated by Django 6.0.4 on 2026-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_investmentproduct_min_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='performance_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Indice de performance (non garanti). Ex: 1.05, 0.97', max_digits=6),
        ),
    ]
