# Generated by Django 6.0.4 on 2026-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_investmentproduct_performance_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='Lien direct https://... (ex: .jpg, .png). Prioritaire si rempli.'),
        ),
    ]
