# Generated by Django 6.0.4 on 2026-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('INVEST', 'Investissement'), ('PAYOUT', 'Crédit investissement'), ('ADJUSTMENT', 'Ajustement')], max_length=20),
        ),
    ]
