# Generated by Django 6.0.4 on 2026-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='payer_phone',
            field=models.CharField(default=1000, help_text='Numéro du client (Mobile Money)', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='method',
            field=models.CharField(choices=[('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money')], max_length=20),
        ),
    ]
