# Generated by Django 6.0.4 on 2026-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_depositrequest_payer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(choices=[('AIRTEL_MONEY', 'Airtel Money'), ('ORANGE_MONEY', 'Orange Money'), ('SIMULATION', 'Simulation')], default='SIMULATION', max_length=20),
        ),
    ]
