# Generated by Django 6.0.4 on 2026-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='duration_days_snapshot',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
