# Generated by Django 6.0.4 on 2026-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_duration_days_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payout_amount_cdf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payout_factor_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
